apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-frontend-deployment
spec:
  template:
    metadata:
      name: app-frontend
      labels:
        app: app-frontend-label
    spec:
      containers:
        - name: app-frontend-container
          image: nttprivateregistry.azurecr.io/docker-local/br-services-platform/software-engineering/integrations/front-end-integration-service:release
          ports:
            - containerPort: 4200
  replicas: 1
  selector:
    matchLabels:
      app: app-frontend-label
